export const ALL_CHANNELS = [
  'category.delete',
  'category.getByName',
  'category.getCategories',
  'category.save',
  'engine.delete',
  'engine.getEngines',
  'engine.save',
  'fileSystem.getBase64Image',
  'fileSystem.getPathForFile',
  'fileSystem.showOpenDialog',
  'import.arachnotron',
  'logger.log',
  'logger.info',
  'logger.error',
  'logger.warn',
  'logger.debug',
  'profile.delete',
  'profile.getProfiles',
  'profile.launchCustom',
  'profile.save',
  'settings.get',
  'settings.getAll',
  'settings.openConfig',
  'settings.set',
  'sgdb.downloadImage',
  'sgdb.getImages',
  'sgdb.queryGames',
  'wad.clearDataDir',
  'wad.getGraphics',
  'wad.getInfo',
] as const;

export type Channel = (typeof ALL_CHANNELS)[number];
