name: Remove old artifacts

on:
  workflow_call:
  workflow_dispatch:

jobs:
  remove-old-artifacts:
    permissions:
      actions: write
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: "1 day"
